"""add prices demand and spot

Revision ID: 1aaba95064a9
Revises: da76cd950013
Create Date: 2024-03-29 19:15:29.599745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aaba95064a9'
down_revision: Union[str, None] = 'da76cd950013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('demand_bitcoin', sa.Float(), nullable=False))
    op.add_column('servers', sa.Column('demand_clore', sa.Float(), nullable=False))
    op.add_column('servers', sa.Column('spot_bitcoin', sa.Float(), nullable=False))
    op.add_column('servers', sa.Column('spot_clore', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'spot_clore')
    op.drop_column('servers', 'spot_bitcoin')
    op.drop_column('servers', 'demand_clore')
    op.drop_column('servers', 'demand_bitcoin')
    # ### end Alembic commands ###
