"""add aboba

Revision ID: 4b480509615e
Revises: 878f9dc3b801
Create Date: 2024-03-29 19:13:49.472827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b480509615e'
down_revision: Union[str, None] = '878f9dc3b801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'aboba')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('aboba', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
