"""initial revision 2

Revision ID: 4d76bb3409f8
Revises: b2d878305052
Create Date: 2024-03-22 18:15:09.781651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d76bb3409f8'
down_revision: Union[str, None] = 'b2d878305052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gpus', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('gpus', 'coin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gpus', 'coin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('gpus', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
