"""add aboba

Revision ID: 878f9dc3b801
Revises: 384157c97a8a
Create Date: 2024-03-29 19:12:25.690810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878f9dc3b801'
down_revision: Union[str, None] = '384157c97a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('aboba', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'aboba')
    # ### end Alembic commands ###
