"""add prices to the server

Revision ID: a745eb873e5b
Revises: e05271c77c3d
Create Date: 2024-03-27 19:20:07.783086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a745eb873e5b'
down_revision: Union[str, None] = 'e05271c77c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('servers', 'gpu_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servers', 'profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('servers', 'gpu_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('servers', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
