"""set gpu name primary

Revision ID: aca79d9481c7
Revises: ea90f9b4ff90
Create Date: 2024-03-24 16:22:50.738723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca79d9481c7'
down_revision: Union[str, None] = 'ea90f9b4ff90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gpus_name_key', 'gpus', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('gpus_name_key', 'gpus', ['name'])
    # ### end Alembic commands ###
