"""initial revision 1

Revision ID: b2d878305052
Revises: 4858a09ab05e
Create Date: 2024-03-22 18:13:51.097557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d878305052'
down_revision: Union[str, None] = '4858a09ab05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gpu_ram', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('coin', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gpu_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('mb', sa.String(), nullable=False),
    sa.Column('cpu', sa.String(), nullable=False),
    sa.Column('cpus', sa.String(), nullable=False),
    sa.Column('ram', sa.Float(), nullable=False),
    sa.Column('disk', sa.String(), nullable=False),
    sa.Column('disk_speed', sa.Float(), nullable=False),
    sa.Column('gpu_id', sa.Integer(), nullable=False),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('net_up', sa.Float(), nullable=False),
    sa.Column('net_down', sa.Float(), nullable=False),
    sa.Column('rented', sa.Boolean(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    op.drop_table('prices')
    op.drop_table('gpus')
    # ### end Alembic commands ###
