"""add prices to the server 1

Revision ID: d57e871c7d6c
Revises: 3bb73dbba94a
Create Date: 2024-03-29 18:58:55.387017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd57e871c7d6c'
down_revision: Union[str, None] = '3bb73dbba94a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
