"""add unique option to gpu name

Revision ID: ea90f9b4ff90
Revises: 4d76bb3409f8
Create Date: 2024-03-23 22:55:08.118387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea90f9b4ff90'
down_revision: Union[str, None] = '4d76bb3409f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'gpus', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gpus', type_='unique')
    # ### end Alembic commands ###
