"""set autoincrement true

Revision ID: f8fe6bd39ce8
Revises: aca79d9481c7
Create Date: 2024-03-24 16:31:45.340715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8fe6bd39ce8'
down_revision: Union[str, None] = 'aca79d9481c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
