"""delete price history model

Revision ID: fd020cf1cee8
Revises: 
Create Date: 2024-04-14 09:23:33.008549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd020cf1cee8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gpu_ram', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('coin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('demand_bitcoin', sa.Float(), nullable=True),
    sa.Column('demand_clore', sa.Float(), nullable=True),
    sa.Column('spot_bitcoin', sa.Float(), nullable=True),
    sa.Column('spot_clore', sa.Float(), nullable=True),
    sa.Column('mb', sa.String(), nullable=False),
    sa.Column('cpu', sa.String(), nullable=False),
    sa.Column('cpus', sa.String(), nullable=False),
    sa.Column('ram', sa.Float(), nullable=False),
    sa.Column('disk', sa.String(), nullable=False),
    sa.Column('disk_speed', sa.Float(), nullable=False),
    sa.Column('gpu_id', sa.Integer(), nullable=True),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('net_up', sa.Float(), nullable=False),
    sa.Column('net_down', sa.Float(), nullable=False),
    sa.Column('rented', sa.Boolean(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    op.drop_table('gpus')
    # ### end Alembic commands ###
